database:
  filters:
    ocorrencia_uf: 'MG'
    start_date: '2024-01-01'
    end_date: '2024-03-31'
    nome_municipio: 
      - 'BELO HORIZONTE'
    crimes:
      - 'FURTO'
      - 'ROUBO'
      - 'HOMICIDIO'
      - 'EXTORSAO'
    exclude:
      instrumento_utilizado_descricao:
        - 'MEIO ELETRONICO (INTERNET OU SMS)'
  columns:
    - '*'
evaluation:
  hit_rate_percentage: 0.1
  train_end_date: '2024-06-30'
  test_end_date:  '2024-08-01'
  temporal_granularity: '1D'
  grid_size: 1000
models:
  # STKDEModel:
  #   slide_window: True
  #   days_past: 180
  #   grid_size_optimization: 1500
  #   municipalities: 
  #     - 'BELO HORIZONTE'
  # ST3DNETModel:
  #   len_closeness: 6
  #   len_period: 0
  #   len_trend: 5
  STHSLModel:
    last_test_date: '2023-08-01'
    batch: 8